spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A Magic 8 Ball App"
name = "magic-eight-ball"
version = "0.1.0"

[[trigger.http]]
route = "/magic-8"
component = "magic-eight-ball"

[component.magic-eight-ball]
source = "target/magic-eight-ball.wasm"
exclude_files = ["**/node_modules"]
ai_models = ["llama2-chat"]
key_value_stores = ["default"]
[component.magic-eight-ball.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]

[[trigger.http]]
route = "/..."
component = "fileserver"

[component.fileserver]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "assets", destination = "/" }]
