spin_manifest_version = "1"
authors = ["Kate Goldenring <kate.goldenring@fermyon.com>"]
description = ""
name = "magic-8-ball"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
# Be sure to set the username, password, and replace `my-redis-instance` for your Redis DB
environment = { REDIS_ADDRESS = "redis://username:password@my-redis-instance.cloud.redislabs.com:1234" }
id = "magic-8-ball"
source = "target/wasm32-wasi/release/magic_8_ball.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/magic-8"
[component.build]
command = "cargo build --target wasm32-wasi --release"

[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.1/spin_static_fs.wasm", digest = "sha256:650376c33a0756b1a52cad7ca670f1126391b79050df0321407da9c741d32375" }
id = "fileserver"
files = [ { source = "../../frontend/", destination = "/" } ]
[component.trigger]
route = "/..."